[wokwi]
version=1
firmware='../../.pio/build/nano/firmware.hex'
elf='../../.pio/build/nano/firmware.elf'

[[chip]]
name = 'bt'  # To use the chip in diagram.json, add a part with "chip-bt" type.
binary = './dist/bt.wasm'