# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = '.pio/build/nanoatmega328/firmware.hex'
elf = '.pio/build/nanoatmega328/firmware.elf'
gdbServerPort=3333
