name: Build Chip

on:
  push:
   # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: tungbt
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build chip
        run: make
      - name: Create a zip archive
        run: cd dist && zip -9 ../chip.zip chip.*
      - name: Upload chip.zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: chip.zip
          asset_name: chip.zip
          asset_content_type: application/zip
